
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSPrincipal", targetNamespace = "http://WebServices.modelo.diewebsiten.com/", wsdlLocation = "http://localhost:8084/DieWebsiten_02/WSPrincipal?wsdl#%7Bhttp%3A%2F%2FWebServices.modelo.diewebsiten.com%2F%7DWSPrincipal")
public class WSPrincipal_Service
    extends Service
{

    private final static URL WSPRINCIPAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(proxy.WSPrincipal_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = proxy.WSPrincipal_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8084/DieWebsiten_02/WSPrincipal?wsdl#%7Bhttp%3A%2F%2FWebServices.modelo.diewebsiten.com%2F%7DWSPrincipal");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8084/DieWebsiten_02/WSPrincipal?wsdl#%7Bhttp%3A%2F%2FWebServices.modelo.diewebsiten.com%2F%7DWSPrincipal', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPRINCIPAL_WSDL_LOCATION = url;
    }

    public WSPrincipal_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSPrincipal_Service() {
        super(WSPRINCIPAL_WSDL_LOCATION, new QName("http://WebServices.modelo.diewebsiten.com/", "WSPrincipal"));
    }

    /**
     * 
     * @return
     *     returns WSPrincipal
     */
    @WebEndpoint(name = "WSPrincipalPort")
    public WSPrincipal getWSPrincipalPort() {
        return super.getPort(new QName("http://WebServices.modelo.diewebsiten.com/", "WSPrincipalPort"), WSPrincipal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSPrincipal
     */
    @WebEndpoint(name = "WSPrincipalPort")
    public WSPrincipal getWSPrincipalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices.modelo.diewebsiten.com/", "WSPrincipalPort"), WSPrincipal.class, features);
    }

}
