
package proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import proxy.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSPrincipal", targetNamespace = "http://WebServices.modelo.diewebsiten.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSPrincipal {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "puntoEntrada", targetNamespace = "http://WebServices.modelo.diewebsiten.com/", className = "proxy.types.PuntoEntrada")
    @ResponseWrapper(localName = "puntoEntradaResponse", targetNamespace = "http://WebServices.modelo.diewebsiten.com/", className = "proxy.types.PuntoEntradaResponse")
    public String puntoEntrada(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
